# Generated by Django 3.1.1 on 2020-09-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetailsModel',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('emp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employeemodel')),
            ],
        ),
    ]
